# Generated by Django 3.2.16 on 2022-10-25 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='family_id',
            field=models.ForeignKey(blank=True, db_column='family_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='families.family'),
        ),
    ]
