# Generated by Django 3.2.16 on 2022-10-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='Text',
            new_name='text',
        ),
    ]
