# Generated by Django 3.2.16 on 2022-11-07 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='family',
        ),
    ]
