# Generated by Django 3.2.16 on 2022-11-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='checklist/photo/', verbose_name='체크리스트 사진'),
        ),
    ]
