# Generated by Django 3.2.16 on 2022-10-30 05:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklist', '0002_rename_text_checklist_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='to_user_id',
        ),
        migrations.AddField(
            model_name='checklist',
            name='to_users_id',
            field=models.ManyToManyField(db_column='to_user_id', related_name='checklists', to=settings.AUTH_USER_MODEL),
        ),
    ]
