# Generated by Django 3.2.16 on 2022-11-02 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_alter_checklist_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='photo',
            field=models.ForeignKey(db_column='photo_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photochecklist', to='checklist.photo'),
        ),
    ]
