# Generated by Django 3.2.16 on 2022-10-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_auto_20221030_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
