# Generated by Django 3.2.16 on 2022-11-17 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatPeriod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('D', 'day'), ('W', 'week'), ('M', 'month'), ('Y', 'year')], max_length=1)),
                ('schedule', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repeatperiod', to='schedule.schedule')),
            ],
        ),
    ]
