# Generated by Django 3.2.16 on 2022-11-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='period',
            field=models.CharField(blank=True, choices=[('W', 'weekly'), ('M', 'monthly'), ('Y', 'yearly')], default=None, max_length=1),
        ),
    ]
