# Generated by Django 3.2.16 on 2022-11-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='important_mark',
            field=models.BooleanField(default=False),
        ),
    ]
