# Generated by Django 3.2.16 on 2022-11-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='today',
        ),
    ]
