# Generated by Django 3.2.16 on 2022-11-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='period',
            field=models.CharField(blank=True, choices=[('W', 'weekly'), ('M', 'monthly'), ('Y', 'yearly')], default=None, max_length=1, null=True),
        ),
    ]
