# Generated by Django 3.2.16 on 2022-11-17 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_repeatperiod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repeatperiod',
            name='schedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='repeatperiod',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to='schedule.repeatperiod'),
        ),
    ]
