# Generated by Django 3.2.16 on 2022-10-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=13, verbose_name='가족이름')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
