# Generated by Django 3.2.16 on 2022-11-10 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='code',
        ),
        migrations.CreateModel(
            name='InvitationCodeFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=33)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitationcode', to='families.family')),
            ],
        ),
    ]
