# Generated by Django 3.2.16 on 2022-11-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrum',
            name='emoji',
            field=models.CharField(max_length=50, verbose_name='오늘의 기분'),
        ),
    ]
