# Generated by Django 3.2.16 on 2022-10-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrum',
            name='today',
            field=models.TextField(blank=True, null=True, verbose_name='오늘 나는'),
        ),
        migrations.AlterField(
            model_name='scrum',
            name='yesterday',
            field=models.TextField(blank=True, null=True, verbose_name='어제 나는'),
        ),
    ]
